# Generated by Django 6.1 on 2026-08-21 20:53

import apps.retrieval.models
import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0005_alter_document_source_type'),
        ('profiles', '0001_initial'),
        ('references', '0001_initial'),
        ('subjects', '0002_enable_rls'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision_id', models.UUIDField()),
                ('revision_ids', models.JSONField(default=list)),
                ('page_start', models.PositiveIntegerField()),
                ('page_end', models.PositiveIntegerField()),
                ('chunk_index', models.PositiveIntegerField(default=0)),
                ('content', models.TextField()),
                ('content_hash', models.CharField(max_length=64)),
                ('source_type', models.CharField(max_length=20)),
                ('embedding', apps.retrieval.models.AdaptiveVectorField(blank=True, dimensions=384, null=True)),
                ('embedding_model', models.CharField(blank=True, max_length=128, null=True)),
                ('embedding_version', models.CharField(blank=True, max_length=64, null=True)),
                ('tsvector_content', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
                ('stale', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='documents.document')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chunks', to='profiles.profile')),
                ('reference_book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chunks', to='references.referencebook')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chunks', to='subjects.subject')),
            ],
            options={
                'ordering': ('document_id', 'chunk_index'),
                'indexes': [models.Index(fields=['document', 'stale'], name='retrieval_n_documen_954c9e_idx'), django.contrib.postgres.indexes.GinIndex(fields=['tsvector_content'], name='idx_notechunk_gin_tsv')],
                'constraints': [models.UniqueConstraint(fields=('revision_id', 'content_hash', 'chunk_index'), name='uniq_notechunk_revision_hash_index')],
            },
        ),
    ]
