# Generated by Django 6.1 on 2026-09-07 23:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='module',
            field=models.CharField(choices=[('NOTE_SPACE', 'NoteSpace'), ('AI_CLASSROOM', 'AI Classroom')], default='NOTE_SPACE', max_length=20),
        ),
        migrations.RemoveConstraint(
            model_name='profile',
            name='uniq_profile_user_name',
        ),
        migrations.AddConstraint(
            model_name='profile',
            constraint=models.UniqueConstraint(fields=('user', 'module', 'name'), name='uniq_profile_user_module_name'),
        ),
    ]
