# Generated by Django 6.1.2 on 2026-10-08 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='agentexecutionlog',
            new_name='agents_agen_profile_95b9e7_idx',
            old_name='agents_agent_profile_crea_123456_idx',
        ),
        migrations.RenameIndex(
            model_name='agentexecutionlog',
            new_name='agents_agen_request_245482_idx',
            old_name='agents_agent_request_123456_idx',
        ),
    ]
