# Generated by Django 6.1 on 2026-08-21 22:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_classroom', '0003_tag_documenttag_tagchangelog_and_more'),
        ('documents', '0006_alter_document_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_revision_id', models.UUIDField()),
                ('source_chunk_id', models.UUIDField()),
                ('difficulty', models.CharField(choices=[('easy', 'easy'), ('medium', 'medium'), ('hard', 'hard')], default='medium', max_length=8)),
                ('prompt', models.TextField()),
                ('options', models.JSONField(default=list)),
                ('answer_index', models.PositiveIntegerField()),
                ('content_hash', models.CharField(max_length=64)),
                ('question_key', models.CharField(max_length=64)),
                ('generation_model', models.CharField(max_length=128)),
                ('prompt_version', models.CharField(max_length=64)),
                ('stale', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='documents.document')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='QuestionTagLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tag_link', to='questions.question')),
                ('tag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='ai_classroom.tag')),
            ],
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(fields=('source_revision_id', 'content_hash', 'question_key'), name='uniq_question_revision_hash_key'),
        ),
    ]
