# Generated by Django 6.1.1 on 2026-09-21 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('mcq', 'Multiple Choice'), ('flashcard', 'Flashcard'), ('short_answer', 'Short Answer'), ('explanation', 'Explanation')], default='mcq', max_length=32),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_index',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
