-- Initialize restricted RLS application role for StudyAI
DO $$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'studyai_app') THEN
        CREATE ROLE studyai_app WITH LOGIN PASSWORD 'studyai_app_pass' NOSUPERUSER NOCREATEDB NOCREATEROLE NOBYPASSRLS;
    END IF;
END
$$;

GRANT CONNECT ON DATABASE studyai TO studyai_app;
GRANT USAGE ON SCHEMA public TO studyai_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO studyai_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO studyai_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO studyai_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO studyai_app;
