# Generated by Django 6.0.8 on 2026-08-22 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_generation_limit', models.PositiveIntegerField(default=500)),
                ('monthly_token_budget', models.PositiveIntegerField(default=100000)),
                ('monthly_cost_budget_usd', models.DecimalField(decimal_places=2, default=50.0, max_digits=10)),
                ('current_month_token_usage', models.PositiveIntegerField(default=0)),
                ('current_month_cost_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('budget_reset_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
