# Generated by Django 6.1 on 2026-08-21 18:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_type', models.CharField(max_length=100)),
                ('resource_type', models.CharField(max_length=100)),
                ('resource_id', models.CharField(max_length=64)),
                ('profile_id', models.UUIDField(blank=True, null=True)),
                ('revision_id', models.UUIDField(blank=True, null=True)),
                ('idempotency_key', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('queued', 'QUEUED'), ('running', 'RUNNING'), ('failed_retryable', 'FAILED_RETRYABLE'), ('failed_dead_letter', 'FAILED_DEAD_LETTER'), ('cancelling', 'CANCELLING'), ('cancelled', 'CANCELLED'), ('succeeded', 'SUCCEEDED')], default='queued', max_length=32)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'created_at'], name='jobs_job_status_277b31_idx'), models.Index(fields=['job_type', 'resource_type', 'resource_id'], name='jobs_job_job_typ_598f4f_idx')],
            },
        ),
    ]
