# Generated by Django 6.1 on 2026-08-21 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='next_retry_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
