# Generated by Django 6.0.8 on 2026-08-22 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_next_retry_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='coalesced_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coalesced_jobs', to='jobs.job'),
        ),
    ]
