# Generated by Django 6.1.1 on 2026-09-09 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_coalesced_from'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobExecutionState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_json', models.JSONField()),
                ('completed_node', models.CharField(choices=[('retrieve', 'Retrieve'), ('draft', 'Draft'), ('gap_detection', 'Gap Detection'), ('gap_fill', 'Gap Fill'), ('citation_stitch', 'Citation Stitch'), ('evidence_verification', 'Evidence Verification'), ('format_output', 'Format Output')], default='retrieve', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_checkpoints', to='jobs.job')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['job', 'created_at'], name='jobs_jobexe_job_id_672397_idx')],
            },
        ),
    ]
