# Generated by Django 6.1 on 2026-08-21 20:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0005_alter_document_source_type'),
        ('subjects', '0002_enable_rls'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceBook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('edition', models.CharField(blank=True, max_length=64)),
                ('isbn', models.CharField(blank=True, max_length=32)),
                ('status', models.CharField(choices=[('draft', 'draft'), ('processing', 'processing'), ('ready', 'ready'), ('failed', 'failed')], default='draft', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reference_book', to='documents.document')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reference_books', to='subjects.subject')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='ReferenceBookChapter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chapter_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('page_range_start', models.PositiveIntegerField()),
                ('page_range_end', models.PositiveIntegerField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='references.referencebook')),
            ],
            options={
                'ordering': ('chapter_number',),
                'constraints': [models.UniqueConstraint(fields=('book', 'chapter_number'), name='uniq_reference_chapter_number')],
            },
        ),
    ]
