# Generated by Django 6.1.1 on 2026-09-29 11:06

import apps.retrieval.models
import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_add_profile_module'),
        ('references', '0001_initial'),
        ('retrieval', '0000_pgvector_extension'),
        ('subjects', '0002_enable_rls'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('source_type', models.CharField(choices=[('TEXTBOOK', 'Textbook'), ('REFERENCE_PDF', 'Reference PDF'), ('LECTURE_MATERIAL', 'Lecture Material')], default='TEXTBOOK', max_length=32)),
                ('file_path', models.CharField(blank=True, default='', max_length=512)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('READY', 'Ready'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('page_count', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('chunk_count', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reference_documents', to='profiles.profile')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reference_documents', to='subjects.subject')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ReferenceChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chunk_index', models.PositiveIntegerField(default=0)),
                ('text', models.TextField()),
                ('content_hash', models.CharField(blank=True, default='', max_length=64)),
                ('embedding', apps.retrieval.models.AdaptiveVectorField(blank=True, dimensions=1024, null=True)),
                ('embedding_model', models.CharField(blank=True, max_length=128, null=True)),
                ('embedding_version', models.CharField(blank=True, max_length=64, null=True)),
                ('page_number', models.PositiveIntegerField(blank=True, null=True)),
                ('chapter', models.CharField(blank=True, default='', max_length=255)),
                ('section', models.CharField(blank=True, default='', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('tsvector_content', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reference_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='references.referencedocument')),
            ],
            options={
                'ordering': ('reference_document_id', 'chunk_index'),
            },
        ),
        migrations.AddIndex(
            model_name='referencedocument',
            index=models.Index(fields=['status', 'subject'], name='references__status_288958_idx'),
        ),
        migrations.AddIndex(
            model_name='referencedocument',
            index=models.Index(fields=['profile', 'status'], name='references__profile_c04b36_idx'),
        ),
        migrations.AddIndex(
            model_name='referencechunk',
            index=models.Index(fields=['reference_document', 'chunk_index'], name='references__referen_98585e_idx'),
        ),
        migrations.AddIndex(
            model_name='referencechunk',
            index=django.contrib.postgres.indexes.GinIndex(fields=['tsvector_content'], name='idx_refchunk_gin_tsv'),
        ),
    ]
