# Generated by Django 6.1 on 2026-08-21 19:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        ('subjects', '0002_enable_rls'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('upload', 'upload'), ('canvas', 'canvas'), ('reference', 'reference')], max_length=20)),
                ('source_type', models.CharField(choices=[('image', 'image'), ('pdf', 'pdf'), ('canvas_page', 'canvas_page')], max_length=20)),
                ('schema_version', models.CharField(default='1', max_length=16)),
                ('reference_book_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='profiles.profile')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='subjects.subject')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='DocumentPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('page_number', models.PositiveIntegerField()),
                ('image_ref', models.CharField(blank=True, max_length=512, null=True)),
                ('current_revision_id', models.UUIDField(blank=True, null=True)),
                ('needs_review', models.BooleanField(default=False)),
                ('ocr_status', models.CharField(choices=[('pending', 'pending'), ('processing', 'processing'), ('completed', 'completed'), ('needs_review', 'needs_review'), ('failed', 'failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='documents.document')),
            ],
            options={
                'ordering': ('page_number',),
            },
        ),
        migrations.CreateModel(
            name='DocumentPageRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision_number', models.PositiveIntegerField()),
                ('content_hash', models.CharField(max_length=64)),
                ('content_snapshot', models.JSONField(default=dict)),
                ('ocr_status', models.CharField(choices=[('pending', 'pending'), ('processing', 'processing'), ('completed', 'completed'), ('needs_review', 'needs_review'), ('failed', 'failed')], default='pending', max_length=20)),
                ('ocr_provider', models.CharField(blank=True, max_length=64, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='documents.documentpage')),
            ],
            options={
                'ordering': ('revision_number',),
            },
        ),
        migrations.CreateModel(
            name='DocumentLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('line_index', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('bbox', models.JSONField(blank=True, null=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('page_revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='documents.documentpagerevision')),
            ],
            options={
                'ordering': ('line_index',),
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['profile', 'created_at'], name='documents_d_profile_cb37d8_idx'),
        ),
        migrations.AddConstraint(
            model_name='documentpage',
            constraint=models.UniqueConstraint(fields=('document', 'page_number'), name='uniq_document_page_number'),
        ),
        migrations.AddConstraint(
            model_name='documentpagerevision',
            constraint=models.UniqueConstraint(fields=('page', 'revision_number'), name='uniq_page_revision_number'),
        ),
        migrations.AddConstraint(
            model_name='documentline',
            constraint=models.UniqueConstraint(fields=('page_revision', 'line_index'), name='uniq_revision_line_index'),
        ),
    ]
