# Generated by Django 6.1 on 2026-08-21 20:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_enable_rls'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentline',
            name='is_heading',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DigitizedDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content_hash', models.CharField(max_length=64)),
                ('revision_ids', models.JSONField(default=list)),
                ('pdf_ref', models.CharField(max_length=512)),
                ('renderer_version', models.CharField(max_length=64)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digitized_documents', to='documents.document')),
            ],
            options={
                'ordering': ('-created_at',),
                'constraints': [models.UniqueConstraint(fields=('document', 'content_hash'), name='uniq_digitized_document_hash')],
            },
        ),
    ]
