# Generated by Django 6.1 on 2026-08-21 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_enable_rls_digitized'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='source_type',
            field=models.CharField(choices=[('image', 'image'), ('pdf', 'pdf'), ('canvas_page', 'canvas_page'), ('reference', 'reference')], max_length=20),
        ),
    ]
