# Generated by Django 6.1.1 on 2026-09-23 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_alter_document_profile'),
        ('notebooks', '0002_enable_rls'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='notebook',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='notebooks.notebook'),
        ),
        migrations.AddField(
            model_name='document',
            name='title',
            field=models.CharField(default='Untitled Note', max_length=255),
        ),
    ]
