# Generated by Django 6.0.8 on 2026-08-22 19:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        ('subjects', '0002_enable_rls'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('cover_image_ref', models.CharField(blank=True, max_length=512, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notebooks', to='profiles.profile')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notebooks', to='subjects.subject')),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='NotebookPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('page_number', models.PositiveIntegerField()),
                ('canvas_state', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='notebooks.notebook')),
            ],
            options={
                'ordering': ('page_number',),
            },
        ),
        migrations.CreateModel(
            name='NotebookLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('line_index', models.PositiveIntegerField()),
                ('points', models.JSONField(default=list)),
                ('color', models.CharField(default='#000000', max_length=20)),
                ('width', models.FloatField(default=2.0)),
                ('tool', models.CharField(default='pen', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='notebooks.notebookpage')),
            ],
            options={
                'ordering': ('line_index',),
            },
        ),
        migrations.AddIndex(
            model_name='notebook',
            index=models.Index(fields=['profile', 'created_at'], name='notebooks_n_profile_0825f1_idx'),
        ),
        migrations.AddConstraint(
            model_name='notebookpage',
            constraint=models.UniqueConstraint(fields=('notebook', 'page_number'), name='uniq_notebook_page_number'),
        ),
        migrations.AddConstraint(
            model_name='notebookline',
            constraint=models.UniqueConstraint(fields=('page', 'line_index'), name='uniq_notebook_page_line_index'),
        ),
    ]
