# Generated by Django 6.1 on 2026-08-21 22:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_classroom', '0003_tag_documenttag_tagchangelog_and_more'),
        ('profiles', '0001_initial'),
        ('questions', '0001_initial'),
        ('subjects', '0002_enable_rls'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('practice', 'practice'), ('mock', 'mock')], default='practice', max_length=16)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='profiles.profile')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tests', to='subjects.subject')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='MasteryScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mastery', models.FloatField(default=0.0)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('correct_count', models.PositiveIntegerField(default=0)),
                ('last_assessed_at', models.DateTimeField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mastery_scores', to='profiles.profile')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mastery_scores', to='subjects.subject')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mastery_scores', to='ai_classroom.tag')),
            ],
            options={
                'ordering': ('tag__stable_key',),
                'constraints': [models.UniqueConstraint(fields=('profile', 'tag'), name='uniq_mastery_profile_tag')],
            },
        ),
        migrations.CreateModel(
            name='TestAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_index', models.PositiveIntegerField()),
                ('correct', models.BooleanField()),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='questions.question')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='tests.testinstance')),
            ],
            options={
                'ordering': ('answered_at',),
                'constraints': [models.UniqueConstraint(fields=('test', 'question'), name='uniq_attempt_per_test_question')],
            },
        ),
        migrations.CreateModel(
            name='TestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_questions', to='questions.question')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_questions', to='tests.testinstance')),
            ],
            options={
                'ordering': ('order',),
                'constraints': [models.UniqueConstraint(fields=('test', 'question'), name='uniq_test_question')],
            },
        ),
    ]
