# Generated by Django 4.2 on 2026-08-24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tests", "0002_phase7_rls"),
    ]

    operations = [
        migrations.AddField(
            model_name="testinstance",
            name="title",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
