# Generated by Django 6.1 on 2026-08-21 19:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        ('subjects', '0002_enable_rls'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanvasSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_id', models.CharField(max_length=64)),
                ('lock_holder', models.CharField(blank=True, max_length=64, null=True)),
                ('lock_generation', models.PositiveIntegerField(default=1)),
                ('lock_expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canvas_sessions', to='profiles.profile')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canvas_sessions', to='subjects.subject')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='CanvasPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('page_number', models.PositiveIntegerField()),
                ('is_finalized', models.BooleanField(default=False)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='canvas.canvassession')),
            ],
            options={
                'ordering': ('page_number',),
            },
        ),
        migrations.CreateModel(
            name='CanvasStroke',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence_order', models.PositiveIntegerField(default=0)),
                ('points', models.JSONField(default=list)),
                ('client_idempotency_key', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strokes', to='canvas.canvaspage')),
            ],
            options={
                'ordering': ('sequence_order', 'created_at'),
            },
        ),
        migrations.AddIndex(
            model_name='canvassession',
            index=models.Index(fields=['profile', 'created_at'], name='canvas_canv_profile_2d04f2_idx'),
        ),
        migrations.AddConstraint(
            model_name='canvaspage',
            constraint=models.UniqueConstraint(fields=('session', 'page_number'), name='uniq_canvas_page_session_number'),
        ),
        migrations.AddIndex(
            model_name='canvasstroke',
            index=models.Index(fields=['page', 'sequence_order'], name='canvas_canv_page_id_72a219_idx'),
        ),
    ]
