# Generated by Django 6.1 on 2026-08-21 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0002_enable_rls'),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='canvassession',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canvas_sessions', to='documents.document'),
        ),
    ]
