# Generated by Django 6.1 on 2026-08-21 21:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0006_alter_document_profile'),
        ('jobs', '0002_job_next_retry_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrichedNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content_hash', models.CharField(max_length=64)),
                ('revision_ids', models.JSONField(default=list)),
                ('provider', models.CharField(max_length=64)),
                ('model', models.CharField(max_length=128)),
                ('prompt_version', models.CharField(max_length=64)),
                ('schema_version', models.CharField(default='v1', max_length=32)),
                ('ai_stale', models.BooleanField(default=False)),
                ('superseded', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enriched_notes', to='documents.document')),
                ('generation_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='jobs.job')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='EnrichedNoteBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('block_index', models.PositiveIntegerField()),
                ('block_type', models.CharField(max_length=32)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('content', models.TextField()),
                ('generation_method', models.CharField(choices=[('llm', 'llm'), ('rule_based', 'rule_based'), ('user_edited', 'user_edited'), ('transcribed', 'transcribed')], max_length=20)),
                ('source_chunk_ids', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enriched_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='ai_classroom.enrichednote')),
            ],
            options={
                'ordering': ('block_index',),
            },
        ),
        migrations.CreateModel(
            name='CitationBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_refs', models.JSONField(default=list)),
                ('verification_status', models.CharField(choices=[('supported', 'supported'), ('partially_supported', 'partially_supported'), ('unsupported', 'unsupported'), ('not_verified', 'not_verified')], default='not_verified', max_length=24)),
                ('verification_score', models.FloatField(blank=True, null=True)),
                ('verifier_version', models.CharField(default='none', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enriched_note_block', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='citation', to='ai_classroom.enrichednoteblock')),
            ],
            options={
                'ordering': ('enriched_note_block__block_index',),
            },
        ),
        migrations.CreateModel(
            name='PromptVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prompt_name', models.CharField(max_length=64)),
                ('version', models.CharField(max_length=16)),
                ('template', models.TextField()),
                ('output_schema_version', models.CharField(max_length=32)),
                ('model', models.CharField(max_length=128)),
                ('configuration', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('prompt_name', '-version'),
                'constraints': [models.UniqueConstraint(fields=('prompt_name', 'version'), name='uniq_prompt_name_version')],
            },
        ),
        migrations.AddIndex(
            model_name='enrichednote',
            index=models.Index(fields=['document', 'created_at'], name='ai_classroo_documen_9cfb93_idx'),
        ),
        migrations.AddConstraint(
            model_name='enrichednote',
            constraint=models.UniqueConstraint(condition=models.Q(('superseded', False)), fields=('document', 'content_hash'), name='uniq_active_enriched_note_hash'),
        ),
    ]
